http:
  routers:
    server:
      rule: 'Host(`hub.slimbouchoucha.tn`) && PathPrefix(`/api`)'
      service: server
      priority: 10
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt

    admin:
      rule: 'Host(`hub.slimbouchoucha.tn`)'
      service: admin
      priority: 1
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt

    superadmin:
      rule: 'Host(`hub-superadmin.slimbouchoucha.tn`)'
      service: superadmin
      priority: 1
      entryPoints: [websecure]
      tls:
        certResolver: letsencrypt

  services:
    server:
      loadBalancer:
        servers:
          - url: 'http://server:3001'

    admin:
      loadBalancer:
        servers:
          - url: 'http://admin:80'

    superadmin:
      loadBalancer:
        servers:
          - url: 'http://superadmin:80'
