/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUsersRouteImport } from './routes/_auth/users'
import { Route as AuthOrgsRouteImport } from './routes/_auth/orgs'
import { Route as AuthOrgsOrgIdRouteImport } from './routes/_auth/orgs.$orgId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgsRoute = AuthOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgsOrgIdRoute = AuthOrgsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AuthOrgsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/orgs': typeof AuthOrgsRouteWithChildren
  '/users': typeof AuthUsersRoute
  '/orgs/$orgId': typeof AuthOrgsOrgIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/orgs': typeof AuthOrgsRouteWithChildren
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
  '/orgs/$orgId': typeof AuthOrgsOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/orgs': typeof AuthOrgsRouteWithChildren
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/orgs/$orgId': typeof AuthOrgsOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/orgs' | '/users' | '/orgs/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/orgs' | '/users' | '/' | '/orgs/$orgId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/orgs'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/orgs/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orgs': {
      id: '/_auth/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthOrgsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orgs/$orgId': {
      id: '/_auth/orgs/$orgId'
      path: '/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthOrgsOrgIdRouteImport
      parentRoute: typeof AuthOrgsRoute
    }
  }
}

interface AuthOrgsRouteChildren {
  AuthOrgsOrgIdRoute: typeof AuthOrgsOrgIdRoute
}

const AuthOrgsRouteChildren: AuthOrgsRouteChildren = {
  AuthOrgsOrgIdRoute: AuthOrgsOrgIdRoute,
}

const AuthOrgsRouteWithChildren = AuthOrgsRoute._addFileChildren(
  AuthOrgsRouteChildren,
)

interface AuthRouteChildren {
  AuthOrgsRoute: typeof AuthOrgsRouteWithChildren
  AuthUsersRoute: typeof AuthUsersRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOrgsRoute: AuthOrgsRouteWithChildren,
  AuthUsersRoute: AuthUsersRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
